### ISSUE TITLE
AttributeError: 'module' object has no attribute '__file__'

### ISSUE THREAD

**Issue by matejc** [teamniteo/bobtemplates.niteoweb#4]
Running this command (taken from readme):

``` bash
> mrbob --config mrbob.ini -O collective.foo bobtemplates:plone
```

I get this traceback before mr.bob asks any questions:

``` bash
Traceback (most recent call last):
  File "/home/matej/bin/mrbob", line 8, in <module>
    load_entry_point('mr.bob==0.1a9', 'console_scripts', 'mrbob')()
  File "/home/matej/workarea/mrbob/lib/python2.7/site-packages/mrbob/cli.py", line 162, in main
    defaults=defaults)
  File "/home/matej/workarea/mrbob/lib/python2.7/site-packages/mrbob/configurator.py", line 138, in __init__
    self.template_dir, self.is_tempdir = parse_template(template)
  File "/home/matej/workarea/mrbob/lib/python2.7/site-packages/mrbob/configurator.py", line 92, in parse_template
    path = resolve_dotted_path(template_name)
  File "/home/matej/workarea/mrbob/lib/python2.7/site-packages/mrbob/configurator.py", line 40, in resolve_dotted_path
    return os.path.join(os.path.dirname(module.__file__), dir_name)
AttributeError: 'module' object has no attribute '__file__'
```

iElectric is convinced that this is not issue of mr.bob

But this procedure works:

``` bash
easy_install -U mr.bob
git clone git://github.com/niteoweb/bobtemplates.niteoweb.git
mrbob -O plone.hud_dummy --config mrbob.ini bobtemplates.niteoweb/bobtemplates/plone/
```

even make command exits with 0.

**Comment by davilima6** [comment]
+1

**Comment by reinhardt** [comment]
+1

**Comment by pigeonflight** [comment]
same issue here. My solution was to use easy_install instead of pip

```
easy_install -U bobtemplates.niteoweb
```

For some reason pip install did not work for me.

**Comment by djowett** [comment]
IIRC I fell back to using a mrbob built by buildout with templates referenced in buildout.cfg as being more well behaved than a pip/easy_install installed mrbob
